"""Supplemental character names and producer roles, with traceable sources.

Maintain these separately from generated birthday-page profiles. Missing birthdays
remain unknown; adding a profile does not create a birthday reminder.
"""

CHARACTER_SUPPLEMENTAL_PROFILES = {
    "美城常务": {
        "name_cn": "美城常务",
        "name_jp": "美城常務",
        "brand": "cinderellagirls",
        "aliases": ["美诚常务", "美城专务", "美城専務"],
        "summary": "346事务所偶像事业部门的统括重役。",
        "source_url": "https://imas-cinderella.com/story/14.html",
        "source_title": "TVアニメ「アイドルマスター シンデレラガールズ」第14話",
    },
    "斋藤孝司": {
        "name_cn": "斋藤孝司",
        "name_jp": "齋藤孝司",
        "brand": "sidem",
        "aliases": ["斎藤孝司", "315社长", "315社長", "SideM社长"],
        "summary": "315事务所社长。",
        "source_url": "https://imas-sidem.com/news/?article_id=62257",
        "source_title": "TVアニメ「アイドルマスター SideM」Blu-ray Disc BOX開封動画公開！",
    },
    "十王邦夫": {
        "name_cn": "十王邦夫",
        "name_jp": "十王 邦夫",
        "brand": "gakuen_idolmaster",
        "aliases": ["初星学园学园长", "初星学園学園長"],
        "summary": "初星学园的创立者及现任学园长。",
        "source_url": "https://idolmaster-official.jp/news/01_10953",
        "source_title": "「学園アイドルマスター」解禁",
    },
    "根绪亚纱里": {
        "name_cn": "根绪亚纱里",
        "name_jp": "根緒 亜紗里",
        "brand": "gakuen_idolmaster",
        "aliases": ["根绪亚沙里"],
        "summary": "初星学园的班主任老师。",
        "source_url": "https://gakuen.idolmaster-official.jp/idol/asari/",
        "source_title": "学園名簿：根緒 亜紗里",
    },
    "美作武史": {
        "name_cn": "美作武史",
        "name_jp": "美作 武史",
        "brand": "sidem",
        "summary": "SideM 新偶像发掘试镜的候选生。",
        "source_url": "https://www.animatetimes.com/news/details.php?id=1449451096",
        "source_title": "「アイドルマスター SideM」初の単独ライブで新情報が続々！",
    },
    "赤羽根P": {
        "name_cn": "赤羽根P",
        "name_jp": "プロデューサー",
        "brand": "the_idolmaster",
        "aliases": ["赤羽根p", "赤羽根制作人", "765动画P", "765アニメP", "バネP", "赤羽根健治P"],
        "summary": "765 动画中的制作人；赤羽根 P 是按声优称呼的别名，并非角色本名。",
        "source_url": "https://www.idolmaster-anime.jp/character/",
        "source_title": "THE IDOLM@STER MOVIE：CHARACTER",
    },
    "武内P": {
        "name_cn": "武内P",
        "name_jp": "プロデューサー",
        "brand": "cinderellagirls",
        "aliases": ["武内p", "武内制作人", "灰姑娘动画P", "346动画P", "武内駿輔P"],
        "summary": "灰姑娘女孩动画中的制作人；武内 P 为匹配用的通称。",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "闪耀色彩P": {
        "name_cn": "闪耀色彩P",
        "name_jp": "プロデューサー",
        "brand": "shinycolors",
        "aliases": ["闪耀色彩p", "闪耀色彩的P", "闪P", "闪p", "闪耀色彩动画P", "夏目P", "夏目p", "シャニP", "シャニアニP", "283动画P"],
        "summary": "闪耀色彩动画中的制作人。",
        "source_url": "https://shinycolors-anime.idolmaster-official.jp/character/",
        "source_title": "シャイニーカラーズ：Character",
    },
    "石川P": {
        "name_cn": "石川P",
        "name_jp": "プロデューサー",
        "brand": "sidem",
        "aliases": ["石川p", "石川制作人", "SideM动画P", "315动画P", "石川界人P"],
        "summary": "SideM 动画中的制作人。",
        "source_url": "https://imas-sidem.com/character/",
        "source_title": "SideM：CHARACTER",
    },
    "百万动画P": {
        "name_cn": "百万动画P",
        "name_jp": "プロデューサー",
        "brand": "millionlive",
        "aliases": ["百万动画p", "百万P", "百万p", "百万制作人", "中村P", "中村p", "源P", "源p", "ミリアニP", "ミリオンライブP"],
        "summary": "百万现场动画中的制作人。",
        "source_url": "https://millionlive-anime.idolmaster-official.jp/news/1020/",
        "source_title": "765プロch 原っぱ通信",
    },
    "今西部长": {
        "name_cn": "今西部长",
        "name_jp": "今西部長",
        "brand": "cinderellagirls",
        "summary": "灰姑娘女孩动画中的 346 事务所部长。",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "训练员": {
        "name_cn": "训练员",
        "name_jp": "トレーナー",
        "brand": "cinderellagirls",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "资深训练员": {
        "name_cn": "资深训练员",
        "name_jp": "ベテラントレーナー",
        "brand": "cinderellagirls",
        "aliases": ["老练训练员"],
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "新人训练员": {
        "name_cn": "新人训练员",
        "name_jp": "ルーキートレーナー",
        "brand": "cinderellagirls",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "石川实": {
        "name_cn": "石川实",
        "name_jp": "石川実",
        "brand": "dearlystars",
        "aliases": ["876社长", "876社長"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "冈本真奈美": {
        "name_cn": "冈本真奈美",
        "name_jp": "岡本まなみ",
        "brand": "dearlystars",
        "aliases": ["岡本真奈美"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "尾崎玲子": {
        "name_cn": "尾崎玲子",
        "name_jp": "尾崎玲子",
        "brand": "dearlystars",
        "aliases": ["尾崎P", "尾崎p"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "武田苍一": {
        "name_cn": "武田苍一",
        "name_jp": "武田蒼一",
        "brand": "dearlystars",
        "aliases": ["武田P", "武田p"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
}
