"""Supplemental character names and producer roles, with traceable sources.

Maintain these separately from generated birthday-page profiles. Missing birthdays
remain unknown; adding a profile does not create a birthday reminder.
"""

CHARACTER_SUPPLEMENTAL_PROFILES = {
    "美城常务": {
        "name_cn": "美城常务",
        "name_jp": "美城常務",
        "brand": "cinderellagirls",
        "aliases": ["美诚常务", "美城专务", "美城専務"],
        "summary": "346事务所偶像事业部门的统括重役。",
        "source_url": "https://imas-cinderella.com/story/14.html",
        "source_title": "TVアニメ「アイドルマスター シンデレラガールズ」第14話",
    },
    "斋藤孝司": {
        "name_cn": "斋藤孝司",
        "name_jp": "齋藤孝司",
        "brand": "sidem",
        "aliases": ["斎藤孝司", "315社长", "315社長", "SideM社长"],
        "summary": "315事务所社长。",
        "source_url": "https://imas-sidem.com/news/?article_id=62257",
        "source_title": "TVアニメ「アイドルマスター SideM」Blu-ray Disc BOX開封動画公開！",
    },
    "十王邦夫": {
        "name_cn": "十王邦夫",
        "name_jp": "十王 邦夫",
        "brand": "gakuen_idolmaster",
        "aliases": ["初星学园学园长", "初星学園学園長"],
        "summary": "初星学园的创立者及现任学园长。",
        "source_url": "https://idolmaster-official.jp/news/01_10953",
        "source_title": "「学園アイドルマスター」解禁",
    },
    "根绪亚纱里": {
        "name_cn": "根绪亚纱里",
        "name_jp": "根緒 亜紗里",
        "brand": "gakuen_idolmaster",
        "aliases": ["根绪亚沙里"],
        "summary": "初星学园的班主任老师。",
        "source_url": "https://gakuen.idolmaster-official.jp/idol/asari/",
        "source_title": "学園名簿：根緒 亜紗里",
    },
    "美作武史": {
        "name_cn": "美作武史",
        "name_jp": "美作 武史",
        "brand": "sidem",
        "summary": "SideM 新偶像发掘试镜的候选生。",
        "source_url": "https://www.animatetimes.com/news/details.php?id=1449451096",
        "source_title": "「アイドルマスター SideM」初の単独ライブで新情報が続々！",
    },
    "赤羽根P": {
        "name_cn": "赤羽根P",
        "name_jp": "プロデューサー",
        "brand": "the_idolmaster",
        "aliases": ["赤羽根p", "赤羽根制作人", "765动画P", "765アニメP", "バネP", "赤羽根健治P", "赤羽根健治p", "赤羽根健治", "2011动画P"],
        "cv": "赤羽根健治",
        "summary": "765 动画中的制作人；赤羽根 P 是按声优称呼的别名，并非角色本名。",
        "source_url": "https://www.idolmaster-anime.jp/character/",
        "source_title": "THE IDOLM@STER MOVIE：CHARACTER",
    },
    "武内P": {
        "name_cn": "武内P",
        "name_jp": "プロデューサー",
        "brand": "cinderellagirls",
        "aliases": ["武内p", "武内制作人", "2015版武内P", "武内駿輔P", "武内駿輔p", "武内骏辅P", "武内骏辅p", "武内骏辅", "武内駿輔", "武內駿輔"],
        "cv": "武内駿輔",
        "summary": "灰姑娘女孩动画中的制作人；武内 P 为匹配用的通称。",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "闪耀色彩P": {
        "name_cn": "闪耀色彩P",
        "name_jp": "プロデューサー",
        "brand": "shinycolors",
        "aliases": ["闪耀色彩p", "闪耀色彩的P", "闪P", "闪p", "闪耀色彩动画P", "夏目P", "夏目p", "シャニP", "シャニアニP", "283动画P", "夏目响平", "夏目響平", "夏目响平P", "夏目響平P"],
        "cv": "夏目響平",
        "summary": "闪耀色彩动画中的制作人。",
        "source_url": "https://shinycolors-anime.idolmaster-official.jp/character/",
        "source_title": "シャイニーカラーズ：Character",
    },
    "石川P": {
        "name_cn": "石川P",
        "name_jp": "プロデューサー",
        "brand": "sidem",
        "aliases": ["石川p", "石川制作人", "SideM动画P", "315动画P", "石川界人P", "石川界人p", "石川界人"],
        "cv": "石川界人",
        "summary": "SideM 动画中的制作人。",
        "source_url": "https://imas-sidem.com/character/",
        "source_title": "SideM：CHARACTER",
    },
    "百万动画P": {
        "name_cn": "百万动画P",
        "name_jp": "プロデューサー",
        "brand": "millionlive",
        "aliases": ["百万动画p", "中村P", "中村p", "源P", "源p", "源太P", "源太p", "中村源太", "中村源太P", "中村源太p"],
        "cv": "中村源太",
        "summary": "百万现场动画中由中村源太配音的制作人，与チーフプロデューサー分开登记；保留既有数据库键。",
        "source_url": "https://millionlive-anime.idolmaster-official.jp/character/",
        "source_title": "ミリオンライブ！：プロデューサー",
    },
    "米内P": {
        "name_cn": "米内P",
        "name_jp": "プロデューサー",
        "brand": "cinderellagirls",
        "aliases": ["米内p", "米內P", "米內p", "U149P", "U149p", "u149P", "u149p", "U149米内P", "U149制作人", "第3艺能课P", "米内佑希", "米內佑希", "米内佑希P"],
        "cv": "米内佑希",
        "summary": "U149 动画中第3艺能课的制作人，按声优称为米内P；与武内P不是同一条记录。",
        "source_url": "https://idolmaster-official.jp/news/01_15341",
        "source_title": "【U149】APかっしー／米内Pによるコミックプロデュース！",
    },
    "百万ChiefP": {
        "name_cn": "百万ChiefP",
        "name_jp": "チーフプロデューサー",
        "brand": "millionlive",
        "aliases": ["百万Chiefp", "百万chiefP", "百万chiefp", "百万Chief赤羽根P", "百万赤羽根P", "百万动画ChiefP", "765 Chief P", "765 Chief p", "チーフプロデューサー", "Chief Producer", "chief producer"],
        "cv": "赤羽根健治",
        "summary": "百万现场动画中由赤羽根健治配音的チーフプロデューサー。按作品形象单独登记，不把泛称百万P关联到这位或中村P。",
        "source_url": "https://millionlive-anime.idolmaster-official.jp/character/",
        "source_title": "ミリオンライブ！：チーフプロデューサー",
    },
    "间岛P": {
        "name_cn": "间岛P",
        "name_jp": "プロデューサー",
        "brand": "the_idolmaster",
        "aliases": ["间岛p", "間島P", "間島p", "间岛淳司", "間島淳司", "间岛淳司P", "間島淳司P", "ぷちますP", "ぷちますp", "小偶像P", "P头制作人"],
        "cv": "間島淳司",
        "summary": "ぷちます！动画中由間島淳司配音的 P 头制作人，与赤羽根P分开登记。",
        "source_url": "https://www.b-ch.com/titles/4075/",
        "source_title": "バンダイチャンネル：ぷちます!! スタッフ・キャスト",
    },
    "学园P": {
        "name_cn": "学园P",
        "name_jp": "プロデューサー",
        "brand": "gakuen_idolmaster",
        "aliases": ["学园p", "学P", "学p", "学マスP", "学マスp", "学园偶像大师P", "学园制作人", "初星学园P", "初星学園P"],
        "summary": "学园偶像大师中就读于初星学园制作人科的玩家主人公。没有登记角色生日，头像由使用者在 WebUI 上传。",
        "source_url": "https://gakuen.idolmaster-official.jp/",
        "source_title": "学園アイドルマスター：プロデューサー科",
    },
    "秋月律子": {
        "aliases": ["秋月律子P", "秋月律子p", "律子P", "律子p", "秋月律子制作人", "秋月律子プロデューサー"],
    },
    "今西部长": {
        "name_cn": "今西部长",
        "name_jp": "今西部長",
        "brand": "cinderellagirls",
        "summary": "灰姑娘女孩动画中的 346 事务所部长。",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "训练员": {
        "name_cn": "训练员",
        "name_jp": "トレーナー",
        "brand": "cinderellagirls",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "资深训练员": {
        "name_cn": "资深训练员",
        "name_jp": "ベテラントレーナー",
        "brand": "cinderellagirls",
        "aliases": ["老练训练员"],
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "新人训练员": {
        "name_cn": "新人训练员",
        "name_jp": "ルーキートレーナー",
        "brand": "cinderellagirls",
        "source_url": "https://imas-cinderella.com/character/",
        "source_title": "シンデレラガールズ：CHARACTER",
    },
    "石川实": {
        "name_cn": "石川实",
        "name_jp": "石川実",
        "brand": "876_pro",
        "aliases": ["876社长", "876社長"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "冈本真奈美": {
        "name_cn": "冈本真奈美",
        "name_jp": "岡本まなみ",
        "brand": "876_pro",
        "aliases": ["岡本真奈美"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "尾崎玲子": {
        "name_cn": "尾崎玲子",
        "name_jp": "尾崎玲子",
        "brand": "876_pro",
        "aliases": ["尾崎P", "尾崎p"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "武田苍一": {
        "name_cn": "武田苍一",
        "name_jp": "武田蒼一",
        "brand": "876_pro",
        "aliases": ["武田P", "武田p"],
        "source_url": "https://w.atwiki.jp/aniwotawiki/pages/30539.html",
        "source_title": "THE IDOLM@STER DearlyStars：その他のキャラクター",
    },
    "贺阳燐羽": {
        "name_cn": "贺阳燐羽",
        "name_jp": "賀陽燐羽",
        "brand": "gakuen_idolmaster",
        "aliases": ["贺阳磷羽", "贺阳凛羽", "极月贺阳燐羽"],
        "summary": "学园偶像大师中极月学园的偶像。",
        "source_url": "https://x.com/gkmas_official/status/1867170916213625339",
        "source_title": "学園アイドルマスター公式：極月学園 アイドル紹介 (1/4) 賀陽燐羽",
    },
    "蓝井抚子": {
        "name_cn": "蓝井抚子",
        "name_jp": "藍井撫子",
        "brand": "gakuen_idolmaster",
        "aliases": ["藍井撫子", "蓝井撫子", "极月蓝井抚子"],
        "summary": "学园偶像大师中极月学园的偶像。",
        "source_url": "https://x.com/gkmas_official/status/1867171802780467620",
        "source_title": "学園アイドルマスター公式：極月学園 アイドル紹介 (2/4) 藍井撫子",
    },
    "白草四音": {
        "name_cn": "白草四音",
        "name_jp": "白草四音",
        "brand": "gakuen_idolmaster",
        "aliases": ["极月白草四音"],
        "summary": "学园偶像大师中极月学园的偶像。",
        "source_url": "https://x.com/gkmas_official/status/1867172254590914641",
        "source_title": "学園アイドルマスター公式：極月学園 アイドル紹介 (3/4) 白草四音",
    },
    "白草月花": {
        "name_cn": "白草月花",
        "name_jp": "白草月花",
        "brand": "gakuen_idolmaster",
        "aliases": ["极月白草月花"],
        "summary": "学园偶像大师中极月学园的偶像。",
        "source_url": "https://x.com/gkmas_official/status/1867172776953700408",
        "source_title": "学園アイドルマスター公式：極月学園 アイドル紹介 (4/4) 白草月花",
    },
    "学园Vo训练员": {
        "name_cn": "学园Vo训练员",
        "name_jp": "Vo トレーナー",
        "brand": "gakuen_idolmaster",
        "aliases": ["Vo训练员", "学Vo训练员", "初星Vo训练员", "学园声乐训练员", "学的声乐训练员", "ボーカルトレーナー"],
        "summary": "初星学园的声乐训练员；与灰姑娘女孩的训练员分别登记。",
        "source_url": "https://x.com/gkmas_official/status/1788152053535306054",
        "source_title": "学園アイドルマスター公式：Vo・Da・Vi トレーナー紹介",
    },
    "学园Da训练员": {
        "name_cn": "学园Da训练员",
        "name_jp": "Da トレーナー",
        "brand": "gakuen_idolmaster",
        "aliases": ["Da训练员", "学Da训练员", "初星Da训练员", "学园舞蹈训练员", "学的舞蹈训练员", "ダンストレーナー"],
        "summary": "初星学园的舞蹈训练员。",
        "source_url": "https://x.com/gkmas_official/status/1788152053535306054",
        "source_title": "学園アイドルマスター公式：Vo・Da・Vi トレーナー紹介",
    },
    "学园Vi训练员": {
        "name_cn": "学园Vi训练员",
        "name_jp": "Vi トレーナー",
        "brand": "gakuen_idolmaster",
        "aliases": ["Vi训练员", "学Vi训练员", "初星Vi训练员", "学园视觉训练员", "学的视觉训练员", "ビジュアルトレーナー"],
        "summary": "初星学园的视觉训练员。",
        "source_url": "https://x.com/gkmas_official/status/1788152053535306054",
        "source_title": "学園アイドルマスター公式：Vo・Da・Vi トレーナー紹介",
    },
    "卓帕卡布拉": {
        "name_cn": "卓帕卡布拉",
        "name_jp": "チュパカブラ",
        "brand": "millionlive",
        "aliases": ["卓帕", "卓柏卡布拉", "丘帕卡布拉", "百万卓帕", "百万吉祥物", "チュパ"],
        "summary": "百万现场剧场时光中登场的吉祥物。",
        "source_url": "https://idolmaster-official.jp/live_event/million10th/goods/act4.php",
        "source_title": "MILLION LIVE! 10thLIVE TOUR 公式物販：チュパカブラ",
    },
    "ぴにゃこら太": {
        "name_cn": "ぴにゃこら太",
        "name_jp": "ぴにゃこら太",
        "brand": "cinderellagirls",
        "aliases": ["灰姑娘龙猫", "灰龙猫", "龙猫", "皮喵可拉太", "匹喵可拉太", "ぴにゃ"],
        "summary": "灰姑娘女孩中登场的吉祥物；“龙猫”为群友匹配用别名。",
        "source_url": "https://idolmaster-official.jp/news/01_11853",
        "source_title": "シンデレラ公式：ぴにゃグリ",
    },
    "呆笔太郎": {
        "name_cn": "呆笔太郎",
        "name_jp": "デビ太郎",
        "brand": "shinycolors",
        "aliases": ["呆比太郎", "恶魔太郎", "闪耀色彩呆笔太郎", "デビタロウ"],
        "summary": "闪耀色彩中登场的吉祥物；日文名字为デビ太郎。",
        "source_url": "https://idolmaster-official.jp/news/01_2154.html",
        "source_title": "シャニマス公式：283フェス2021 初出時デビ太郎映像を公開",
    },
}
