# Reviewed name aliases and romanizations from public Moegirl infoboxes.
# Japanese identity was checked against the existing actor catalogue.
VOICE_ACTOR_NAMES = {'va:10014': {'aliases': ['天崎滉平', '天﨑 滉平'],
              'romanized_names': ['Amasaki Kōhei'],
              'sources': ['https://zh.moegirl.org.cn/%E5%A4%A9%E5%B4%8E%E6%BB%89%E5%B9%B3']},
 'va:10186': {'aliases': ['儿玉卓也', '児玉 卓也', '兒玉卓也'],
              'romanized_names': ['Kodama Takuya'],
              'sources': ['https://zh.moegirl.org.cn/%E5%84%BF%E7%8E%89%E5%8D%93%E4%B9%9F']},
 'va:10270': {'aliases': ['泰勇气', '泰 勇気', '泰勇氣'],
              'romanized_names': ['Tai Yuuki'],
              'sources': ['https://zh.moegirl.org.cn/%E6%B3%B0%E5%8B%87%E6%B0%94']},
 'va:10357': {'aliases': ['中岛ヨシキ', '中島 ヨシキ', '中島ヨシキ', '中岛 ヨシキ'],
              'romanized_names': ['Nakajima Yoshiki'],
              'sources': ['https://zh.moegirl.org.cn/%E4%B8%AD%E5%B2%9B%E3%83%A8%E3%82%B7%E3%82%AD']},
 'va:10457': {'aliases': ['增元拓也', '増元 拓也'],
              'romanized_names': ['Masumoto Takuya'],
              'sources': ['https://zh.moegirl.org.cn/%E5%A2%9E%E5%85%83%E6%8B%93%E4%B9%9F']},
 'va:10519': {'aliases': ['矢野奖吾', '矢野 奨吾', '矢野獎吾'],
              'romanized_names': ['Yano Shōgo'],
              'sources': ['https://zh.moegirl.org.cn/%E7%9F%A2%E9%87%8E%E5%A5%96%E5%90%BE']},
 'va:10546': {'aliases': ['渡辺纮', '渡辺 紘', '渡辺紘', '渡辺 纮'],
              'romanized_names': ['Watanabe Hiroshi'],
              'sources': ['https://zh.moegirl.org.cn/%E6%B8%A1%E8%BE%BA%E7%BA%AE']},
 'va:10650': {'aliases': ['伊瀬结陆', '伊瀬 結陸', '伊瀬結陸', '伊瀬 结陆'],
              'romanized_names': ['Ise Yūri'],
              'sources': ['https://zh.moegirl.org.cn/%E4%BC%8A%E7%80%AC%E7%BB%93%E9%99%86']},
 'va:10711': {'aliases': ['宫﨑雅也', '宮﨑 雅也', '宮﨑雅也', '宫﨑 雅也'],
              'romanized_names': ['Miyazaki Masaya'],
              'sources': ['https://zh.moegirl.org.cn/%E5%AE%AB%EF%A8%91%E9%9B%85%E4%B9%9F']},
 'va:20021': {'aliases': ['麻仓もも', '麻倉 もも', '麻倉もも', '麻仓 もも'],
              'romanized_names': ['Asakura Momo'],
              'sources': ['https://zh.moegirl.org.cn/%E9%BA%BB%E4%BB%93%E3%82%82%E3%82%82']},
 'va:20096': {'aliases': ['上坂堇', '上坂 すみれ'],
              'romanized_names': ['Uesaka Sumire'],
              'sources': ['https://zh.moegirl.org.cn/%E4%B8%8A%E5%9D%82%E5%A0%87']},
 'va:20224': {'aliases': ['黑泽朋世', '黒沢 ともよ', '黑澤朋世'],
              'romanized_names': ['Kurosawa Tomoyo'],
              'sources': ['https://zh.moegirl.org.cn/%E9%BB%91%E6%B3%BD%E6%9C%8B%E4%B8%96']},
 'va:20230': {'aliases': ['小岩井小鸟', '小岩井 ことり', '小巖井小鳥', '小巖井 ことり'],
              'romanized_names': ['Koiwai Kotori'],
              'sources': ['https://zh.moegirl.org.cn/%E5%B0%8F%E5%B2%A9%E4%BA%95%E5%B0%8F%E9%B8%9F']},
 'va:20347': {'aliases': ['铃木みのり', '鈴木 みのり', '鈴木みのり', '铃木 みのり'],
              'romanized_names': ['Suzuki Minori'],
              'sources': ['https://zh.moegirl.org.cn/%E9%93%83%E6%9C%A8%E3%81%BF%E3%81%AE%E3%82%8A']},
 'va:20381': {'aliases': ['高桥智秋', 'たかはし 智秋', '高橋智秋'],
              'romanized_names': ['Takahashi Chiaki'],
              'sources': ['https://zh.moegirl.org.cn/%E9%AB%98%E6%A1%A5%E6%99%BA%E7%A7%8B']},
 'va:20407': {'aliases': ['田所梓', '田所 あずさ'],
              'romanized_names': ['Tadokoro Azusa'],
              'sources': ['https://zh.moegirl.org.cn/%E7%94%B0%E6%89%80%E6%A2%93']},
 'va:20408': {'aliases': ['田中爱美', '田中 あいみ', '田中愛美'],
              'romanized_names': ['Tanaka Aimi'],
              'sources': ['https://zh.moegirl.org.cn/%E7%94%B0%E4%B8%AD%E7%88%B1%E7%BE%8E']},
 'va:20417': {'aliases': ['田边留依', '田辺 留依', '田邊留依'],
              'romanized_names': ['Tanabe Rui'],
              'sources': ['https://zh.moegirl.org.cn/%E7%94%B0%E8%BE%B9%E7%95%99%E4%BE%9D']},
 'va:20455': {'aliases': ['户田惠', '戸田 めぐみ', '戶田惠'],
              'romanized_names': ['Toda Megumi'],
              'sources': ['https://zh.moegirl.org.cn/%E6%88%B7%E7%94%B0%E6%83%A0']},
 'va:20512': {'aliases': ['新田日和', '新田 ひより'],
              'romanized_names': ['Nitta Hiyori'],
              'sources': ['https://zh.moegirl.org.cn/%E6%96%B0%E7%94%B0%E6%97%A5%E5%92%8C']},
 'va:20536': {'aliases': ['滨崎奈奈', '浜崎 奈々', '濱崎奈奈'],
              'romanized_names': ['Hamasaki Nana'],
              'sources': ['https://zh.moegirl.org.cn/%E6%BB%A8%E5%B4%8E%E5%A5%88%E5%A5%88']},
 'va:20545': {'aliases': ['原岛明里', '原嶋 あかり'],
              'romanized_names': ['Harashima Akari'],
              'sources': ['https://zh.moegirl.org.cn/%E5%8E%9F%E5%B2%9B%E6%98%8E%E9%87%8C']},
 'va:20547': {'aliases': ['原田瞳', '原田 ひとみ'],
              'romanized_names': ['Harada Hitomi'],
              'sources': ['https://zh.moegirl.org.cn/%E5%8E%9F%E7%94%B0%E7%9E%B3']},
 'va:20582': {'aliases': ['藤井幸代', '藤井 ゆきよ'],
              'romanized_names': ['Fujii Yukiyo'],
              'sources': ['https://zh.moegirl.org.cn/%E8%97%A4%E4%BA%95%E5%B9%B8%E4%BB%A3']},
 'va:20694': {'aliases': ['山崎遥', '山崎 はるか', '山崎遙'],
              'romanized_names': ['Yamazaki Haruka'],
              'sources': ['https://zh.moegirl.org.cn/%E5%B1%B1%E5%B4%8E%E9%81%A5']},
 'va:20733': {'aliases': ['佳村遥', '佳村 はるか', '佳村遙'],
              'romanized_names': ['Yoshimura Haruka'],
              'sources': ['https://zh.moegirl.org.cn/%E4%BD%B3%E6%9D%91%E9%81%A5']},
 'va:20788': {'aliases': ['黑木穗乃香', '黒木 ほの香'],
              'romanized_names': ['Kuroki Honoka'],
              'sources': ['https://zh.moegirl.org.cn/%E9%BB%91%E6%9C%A8%E7%A9%97%E4%B9%83%E9%A6%99']},
 'va:20792': {'aliases': ['河野日和', '河野 ひより'],
              'romanized_names': ['Kōno Hiyori'],
              'sources': ['https://zh.moegirl.org.cn/%E6%B2%B3%E9%87%8E%E6%97%A5%E5%92%8C']},
 'va:20813': {'aliases': ['凉本あきほ', '涼本 あきほ', '涼本あきほ', '凉本 あきほ'],
              'romanized_names': ['Suzumoto Akiho'],
              'sources': ['https://zh.moegirl.org.cn/%E5%87%89%E6%9C%AC%E3%81%82%E3%81%8D%E3%81%BB']},
 'va:20839': {'aliases': ['野口百合', 'のぐち ゆり'],
              'romanized_names': ['Noguchi Yuri'],
              'sources': ['https://zh.moegirl.org.cn/%E9%87%8E%E5%8F%A3%E7%99%BE%E5%90%88']},
 'va:20846': {'aliases': ['春咲暖', '春咲 暖'],
              'romanized_names': ['Harusaki Non'],
              'sources': ['https://zh.moegirl.org.cn/%E6%98%A5%E5%92%B2%E6%9A%96']},
 'va:20869': {'aliases': ['八卷安奈', '八巻 アンナ'],
              'romanized_names': ['Yamaki Anna'],
              'sources': ['https://zh.moegirl.org.cn/%E5%85%AB%E5%8D%B7%E5%AE%89%E5%A5%88']},
 'va:20966': {'aliases': ['伊达小百合', '伊達 さゆり', '伊達小百合', '伊达 さゆり'],
              'romanized_names': ['Date Sayuri'],
              'sources': ['https://zh.moegirl.org.cn/%E4%BC%8A%E8%BE%BE%E5%B0%8F%E7%99%BE%E5%90%88']},
 'va:20967': {'aliases': ['集贝はな', '集貝 はな', '集貝はな', '集贝 はな'],
              'romanized_names': ['Tamegai Hana'],
              'sources': ['https://zh.moegirl.org.cn/%E9%9B%86%E8%B4%9D%E3%81%AF%E3%81%AA']},
 'va:20970': {'aliases': ['都丸千代', '都丸 ちよ'],
              'romanized_names': ['Tomaru Chiyo'],
              'sources': ['https://zh.moegirl.org.cn/%E9%83%BD%E4%B8%B8%E5%8D%83%E4%BB%A3']},
 'va:20978': {'aliases': ['春濑夏美', '春瀬 なつみ', '春瀨夏美'],
              'romanized_names': ['Haruse Natsumi'],
              'sources': ['https://zh.moegirl.org.cn/%E6%98%A5%E6%BF%91%E5%A4%8F%E7%BE%8E']},
 'va:21003': {'aliases': ['蓝原ことみ', '藍原 ことみ', '藍原ことみ', '蓝原 ことみ'],
              'romanized_names': ['Aihara Kotomi'],
              'sources': ['https://zh.moegirl.org.cn/%E8%93%9D%E5%8E%9F%E3%81%93%E3%81%A8%E3%81%BF']},
 'va:21018': {'aliases': ['梅泽めぐ', '梅澤 めぐ', '梅澤めぐ', '梅泽 めぐ'],
              'romanized_names': [],
              'sources': ['https://zh.moegirl.org.cn/%E6%A2%85%E6%B3%BD%E3%82%81%E3%81%90']},
 'va:21129': {'aliases': ['天音缘', '天音 ゆかり', '天音緣'],
              'romanized_names': ['Amane Yukari'],
              'sources': ['https://zh.moegirl.org.cn/%E5%A4%A9%E9%9F%B3%E7%BC%98']},
 'va:21133': {'aliases': ['饭田ヒカル', '飯田 ヒカル', '飯田ヒカル', '饭田 ヒカル'],
              'romanized_names': ['Iida Hikaru'],
              'sources': ['https://zh.moegirl.org.cn/%E9%A5%AD%E7%94%B0%E3%83%92%E3%82%AB%E3%83%AB']},
 'va:21138': {'aliases': ['伊藤舞音', '伊藤 舞音'],
              'romanized_names': ['Itō Mao'],
              'sources': ['https://zh.moegirl.org.cn/%E4%BC%8A%E8%97%A4%E8%88%9E%E9%9F%B3']},
 'va:21142': {'aliases': ['薄井友里', '薄井 友里', '薄井友裏', '薄井 友裏'],
              'romanized_names': ['Usui Yuri'],
              'sources': ['https://zh.moegirl.org.cn/%E8%96%84%E4%BA%95%E5%8F%8B%E9%87%8C']},
 'va:21149': {'aliases': ['小鹿奈绪', '小鹿 なお', '小鹿奈緒'],
              'romanized_names': ['Ojika Nao'],
              'sources': ['https://zh.moegirl.org.cn/%E5%B0%8F%E9%B9%BF%E5%A5%88%E7%BB%AA']},
 'va:21155': {'aliases': ['川村玲奈', '川村 玲奈'],
              'romanized_names': ['Kawamura Reina'],
              'sources': ['https://zh.moegirl.org.cn/%E5%B7%9D%E6%9D%91%E7%8E%B2%E5%A5%88']},
 'va:21206': {'aliases': ['长月あおい', '長月 あおい', '長月あおい', '长月 あおい'],
              'romanized_names': ['Nagatsuki Aoi'],
              'sources': ['https://zh.moegirl.org.cn/%E9%95%BF%E6%9C%88%E3%81%82%E3%81%8A%E3%81%84']},
 'va:21211': {'aliases': ['七濑䌷', '七瀬 つむぎ', '七瀨紬'],
              'romanized_names': ['Nanase Tsumugi'],
              'sources': ['https://zh.moegirl.org.cn/%E4%B8%83%E6%BF%91%E4%8C%B7']},
 'va:21218': {'aliases': ['花岩香奈', '花岩 香奈', '花巖香奈', '花巖 香奈'],
              'nickname_note': 'iwa is the user-requested community nickname for 花岩 香奈.',
              'nicknames': ['iwa'],
              'romanized_names': ['Hanaiwa Kana'],
              'sources': ['https://zh.moegirl.org.cn/%E8%8A%B1%E5%B2%A9%E9%A6%99%E5%A5%88']},
 'va:21223': {'aliases': ['阳高真白', '陽高 真白', '陽高真白', '阳高 真白'],
              'romanized_names': ['Hitaka Mashiro'],
              'sources': ['https://zh.moegirl.org.cn/%E9%98%B3%E9%AB%98%E7%9C%9F%E7%99%BD']},
 'va:21234': {'aliases': ['松田彩音', '松田 彩音'],
              'romanized_names': ['Matsuda Ayane'],
              'sources': ['https://zh.moegirl.org.cn/%E6%9D%BE%E7%94%B0%E5%BD%A9%E9%9F%B3']},
 'va:21240': {'aliases': ['凑みや', '湊 みや', '湊みや', '凑 みや'],
              'romanized_names': ['Minato Miya'],
              'sources': ['https://zh.moegirl.org.cn/%E5%87%91%E3%81%BF%E3%82%84']},
 'va:imas-2a49647d7bb5': {'aliases': ['金子真由美', '金子 真由美'],
                          'romanized_names': ['Kaneko Mayumi'],
                          'sources': ['https://zh.moegirl.org.cn/%E9%87%91%E5%AD%90%E7%9C%9F%E7%94%B1%E7%BE%8E']},
 'va:imas-535c554a20a6': {'aliases': ['中泽美娜', '中澤 ミナ', '中澤美娜', '中泽 ミナ'],
                          'romanized_names': ['Nakazawa Mina'],
                          'sources': ['https://zh.moegirl.org.cn/%E4%B8%AD%E6%B3%BD%E7%BE%8E%E5%A8%9C']},
 'va:imas-8e090b38df10': {'aliases': ['长野佑纪', '長野 佑紀', '長野佑紀', '长野 佑纪'],
                          'romanized_names': ['Nagano Yuki'],
                          'sources': ['https://zh.moegirl.org.cn/%E9%95%BF%E9%87%8E%E4%BD%91%E7%BA%AA']},
 'va:imas-b6694c21bb64': {'aliases': ['卢婷', 'ルゥ ティン', '盧婷'],
                          'romanized_names': ['Ru Thing'],
                          'sources': ['https://zh.moegirl.org.cn/%E5%8D%A2%E5%A9%B7']},
 'va:imas-f27f3b439c85': {'aliases': ['关口理咲', '関口 理咲', '關口理咲'],
                          'romanized_names': ['Sekiguchi Risa'],
                          'sources': ['https://zh.moegirl.org.cn/%E5%85%B3%E5%8F%A3%E7%90%86%E5%92%B2']}}
