# Reviewed Chinese search aliases matched through official character CV pages.
# These are aliases, not replacements for the official Japanese display names.
VOICE_ACTOR_LINKS = {'va:10014': {'aliases': ['天崎滉平'],
              'name': '天﨑 滉平',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40027']},
 'va:10186': {'aliases': ['儿玉卓也'],
              'name': '児玉 卓也',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40011']},
 'va:10357': {'aliases': ['中岛良树'],
              'name': '中島 ヨシキ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40044']},
 'va:10406': {'aliases': ['巴莱塔·裕'],
              'name': 'バレッタ 裕',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40037']},
 'va:10429': {'aliases': ['古畑惠介'],
              'name': '古畑 恵介',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40031']},
 'va:10457': {'aliases': ['增元拓也'],
              'name': '増元 拓也',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40028']},
 'va:10519': {'aliases': ['矢野奖吾'],
              'name': '矢野 奨吾',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40013']},
 'va:10546': {'aliases': ['渡边纮'],
              'name': '渡辺 紘',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/40025']},
 'va:10650': {'aliases': ['伊濑结陆'],
              'name': '伊瀬 結陸',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/250001']},
 'va:10711': {'aliases': ['宫崎雅也'],
              'name': '宮﨑 雅也',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/250002']},
 'va:20021': {'aliases': ['麻仓桃'],
              'name': '麻倉 もも',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30027']},
 'va:20096': {'aliases': ['上坂堇'],
              'name': '上坂 すみれ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20009']},
 'va:20224': {'aliases': ['黑泽朋世'],
              'name': '黒沢 ともよ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20005']},
 'va:20230': {'aliases': ['小岩井小鸟'],
              'name': '小岩井 ことり',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30018']},
 'va:20347': {'aliases': ['铃木实里'],
              'name': '鈴木 みのり',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20139']},
 'va:20381': {'aliases': ['高桥智秋'],
              'name': 'たかはし 智秋',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/10012']},
 'va:20384': {'aliases': ['高桥未奈美'],
              'name': '髙橋 ミナミ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30028']},
 'va:20407': {'aliases': ['田所梓'],
              'name': '田所 あずさ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30034']},
 'va:20408': {'aliases': ['田中爱美'],
              'name': '田中 あいみ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/240001']},
 'va:20417': {'aliases': ['田边留依'],
              'name': '田辺 留依',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20012']},
 'va:20455': {'aliases': ['户田惠'],
              'name': '戸田 めぐみ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30030']},
 'va:20512': {'aliases': ['新田日和'],
              'name': '新田 ひより',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20109']},
 'va:20536': {'aliases': ['滨崎奈奈'],
              'name': '浜崎 奈々',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30029']},
 'va:20545': {'aliases': ['原岛明里'],
              'name': '原嶋 あかり',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30022']},
 'va:20547': {'aliases': ['原田瞳'],
              'name': '原田 ひとみ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20110']},
 'va:20582': {'aliases': ['藤井幸代'],
              'name': '藤井 ゆきよ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30020']},
 'va:20694': {'aliases': ['山崎遥'],
              'name': '山崎 はるか',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/30004']},
 'va:20733': {'aliases': ['佳村遥'],
              'name': '佳村 はるか',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20086']},
 'va:20788': {'aliases': ['黑木穗乃香'],
              'name': '黒木 ほの香',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/50005']},
 'va:20792': {'aliases': ['河野日和'],
              'name': '河野 ひより',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/50009']},
 'va:20813': {'aliases': ['凉本秋穗'],
              'name': '涼本 あきほ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/50002']},
 'va:20839': {'aliases': ['野口百合'],
              'name': 'のぐち ゆり',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20029']},
 'va:20869': {'aliases': ['八卷安奈'],
              'name': '八巻 アンナ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/50012']},
 'va:20918': {'aliases': ['二宫结衣'],
              'name': '二ノ宮 ゆい',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20175']},
 'va:20967': {'aliases': ['集贝花'],
              'name': '集貝 はな',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20154']},
 'va:20970': {'aliases': ['都丸千代'],
              'name': '都丸 ちよ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20080']},
 'va:20978': {'aliases': ['春濑夏美'],
              'name': '春瀬 なつみ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20187']},
 'va:21003': {'aliases': ['蓝原琴美'],
              'name': '藍原 ことみ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20019']},
 'va:21018': {'aliases': ['梅泽惠'],
              'name': '梅澤 めぐ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/20106']},
 'va:21129': {'aliases': ['天音缘', '天音縁', '天音緣'],
              'name': '天音 ゆかり',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/60013']},
 'va:21133': {'aliases': ['饭田光', '飯田光'],
              'name': '飯田 ヒカル',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/60003']},
 'va:21206': {'aliases': ['长月葵', '長月葵'],
              'name': '長月 あおい',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/60001']},
 'va:21211': {'aliases': ['七濑䌷', '七濑紬', '七瀬紬'],
              'name': '七瀬 つむぎ',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/60004']},
 'va:21240': {'aliases': ['凑美也'],
              'name': '湊 みや',
              'sources': ['https://idollist.idolmaster-official.jp/search/detail/60007']},
 'va:imas-2a49647d7bb5': {'aliases': ['金子真由美'],
                          'name': '金子 真由美',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20138']},
 'va:imas-4e3bd8a1a18c': {'aliases': ['杜野真子'],
                          'name': '杜野 まこ',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20134']},
 'va:imas-535c554a20a6': {'aliases': ['中泽美娜'],
                          'name': '中澤 ミナ',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20077']},
 'va:imas-6027d73bc59a': {'aliases': ['今井麻夏'],
                          'name': '今井 麻夏',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20076']},
 'va:imas-7c7fd909a14c': {'aliases': ['春野七海'],
                          'name': '春野 ななみ',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20023']},
 'va:imas-8e090b38df10': {'aliases': ['长野佑纪'],
                          'name': '長野 佑紀',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20063']},
 'va:imas-9466e37218b5': {'aliases': ['嘉山未纱'],
                          'name': '嘉山 未紗',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20189']},
 'va:imas-b6694c21bb64': {'aliases': ['卢婷'],
                          'name': 'ルゥ ティン',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20081']},
 'va:imas-f27f3b439c85': {'aliases': ['关口理咲'],
                          'name': '関口 理咲',
                          'sources': ['https://idollist.idolmaster-official.jp/search/detail/20090']}}
