"""Cache the public hexagon avatars used by the official My Desk page."""
from __future__ import annotations

import argparse
import ast
import collections
import io
import json
import pprint
import re
import sys
import unicodedata
from pathlib import Path

import httpx
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
CATALOGUE_URL = "https://idolmaster-official.jp/cdn/jsons/idols/idol_list.json"
ICON_BASE = "https://idolmaster-official.jp/assets/img/idol/hexagon/"


def read_mapping(path: Path, variable: str) -> dict:
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == variable for target in node.targets):
            return ast.literal_eval(node.value)
    return {}


def normalize_name(value: str) -> str:
    value = unicodedata.normalize("NFKC", str(value))
    while re.search(r"\([^()]*\)", value):
        value = re.sub(r"\([^()]*\)", "", value)
    value = re.split(r"[、,;/／]", value)[0]
    return re.sub(r"[\s・·.]+", "", value).casefold()


def build_mapping(rows: list[dict]) -> tuple[dict[str, dict], list[dict]]:
    profiles = read_mapping(ROOT / "character_profiles.py", "CHARACTER_PROFILES")
    assets = read_mapping(ROOT / "character_assets.py", "CHARACTER_IMAGE_ASSETS")
    aliases = read_mapping(ROOT / "tools" / "fetch_portrait_assets.py", "SPECIAL_NAME_ALIASES")
    aliases.update({"エミリー": "艾米莉·斯图亚特", "詩花": "诗花"})
    index: dict[str, set[str]] = collections.defaultdict(set)
    for name in set(profiles) | set(assets):
        profile = profiles.get(name, {})
        for candidate in [name, profile.get("name_jp", ""), profile.get("raw", {}).get("姓名", "")]:
            if candidate:
                index[normalize_name(candidate)].add(name)
    for japanese, chinese in aliases.items():
        if chinese in profiles or chinese in assets:
            index[normalize_name(japanese)].add(chinese)
    result, unmatched = {}, []
    for row in rows:
        names = index.get(normalize_name(row["idol_name"]), set())
        if len(names) != 1:
            unmatched.append({"name": row["idol_name"], "code": row["idol_code"]})
            continue
        brand, code = row["brand_code"].lower(), row["idol_code"]
        if not re.fullmatch(r"[a-z]+", brand) or not re.fullmatch(r"[a-z0-9_]+", code):
            raise ValueError("Unexpected official avatar path")
        filename = f"{brand}/{code}.png"
        result[next(iter(names))] = {**row, "filename": filename, "url": ICON_BASE + filename}
    return result, unmatched


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--icons-dir", type=Path, default=ROOT / "assets" / "tantou_icons")
    parser.add_argument("--catalogue-file", type=Path)
    parser.add_argument("--mapping-only", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()
    with httpx.Client(follow_redirects=True, timeout=20) as client:
        if args.catalogue_file:
            rows = json.loads(args.catalogue_file.read_text(encoding="utf-8"))
        else:
            response = client.get(CATALOGUE_URL)
            response.raise_for_status()
            rows = response.json()
        if not isinstance(rows, list) or len(rows) < 300:
            raise ValueError("Official catalogue is incomplete; existing mapping was preserved")
        mapping, unmatched = build_mapping(rows)
        if unmatched:
            print("Unmatched (no fuzzy assignments):", unmatched)
        if not args.mapping_only:
            failures = []
            for index, (name, record) in enumerate(sorted(mapping.items()), 1):
                path = args.icons_dir / record["filename"]
                if path.exists() and not args.overwrite:
                    continue
                try:
                    response = client.get(record["url"])
                    response.raise_for_status()
                    with Image.open(io.BytesIO(response.content)) as image:
                        if image.format != "PNG":
                            raise ValueError("Expected PNG")
                        image.verify()
                    path.parent.mkdir(parents=True, exist_ok=True)
                    temporary = path.with_suffix(".tmp")
                    temporary.write_bytes(response.content)
                    temporary.replace(path)
                except Exception as exc:
                    failures.append(name)
                    print(f"Failed {name}: {type(exc).__name__}")
                if index % 50 == 0:
                    print(f"Avatars: {index}/{len(mapping)}", flush=True)
            if failures:
                print("Missing avatars:", failures)
        text = "# Generated by tools/fetch_tantou_icons.py from the public official catalogue.\n"
        text += f"# Catalogue: {CATALOGUE_URL}\n"
        text += "CHARACTER_TANTOU_ICONS = " + pprint.pformat(mapping, sort_dicts=True, width=120) + "\n"
        (ROOT / "character_tantou_icons.py").write_text(text, encoding="utf-8")
        print(f"Mapped {len(mapping)}/{len(rows)} official avatars to local character names")


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    main()
